# container 1 deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/advance-cloud-assignment/csci5409-assignment/csci5409-service-1:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: data-volume
              mountPath: /shaik_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc
---
# service 1 for container 1
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer
---
# service 2 for container 2
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
# persistene volume for the containers
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: assignment-cluster-disk
    fsType: ext4
---
# persistent volume clain for host-pv

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Set the desired storage size
  storageClassName: standard
  selector:
    matchLabels:
      name: host-pv